name: LernSpigot
author: TantaiHaha
api-version: 1.18
version: 1.0
main: com.lern.Main
description: Made For Lern Spigot Plugin

commands:
   modewand:
      dsecription: give Mode Wand
      usage: /modewand
   wc:
      description : World Config GUI
      usage: /wc
   r: 
      description : Reload Server
      usage : /r
   t: 
      description : test commands
      usage : /t
   locateplayer:
      description: Use for locate Player
      usage: /loacteplayer <Action> <Value>