name: LernSpigot
author: TantaiHaha
api-version: 1.18
version: 1.0.1
main: com.lern.Main
description: Made For Lern Spigot Plugin

commands:
   modewand:
      dsecription: give Mode Wand
      usage: /modewand
   wc:
      description : World Config GUI
      usage: /wc